### ISSUE TITLE
Update the binaries

### ISSUE THREAD

**Issue by justanotheranonymoususer** [Nukem9/SwissArmyKnife#4]
Here:
https://github.com/Nukem9/SwissArmyKnife/releases

**Comment by justanotheranonymoususer** [comment]
OK, I installed VS 2015 and compiled the project.
You can get the binaries here:
https://mega.nz/#!U8tBGJTa!V0Dgny76-K0UlhKJc2xlLJAIrMIIK--pCu94HM1Yp48

**Comment by Nukem9** [comment]
I compiled my own binaries and uploaded them - hope you don't mind.
