### ISSUE TITLE
Signature creation problems

### ISSUE THREAD

**Issue by moradin** [Nukem9/SwissArmyKnife#6]
Maybe I'm missing something but the signature creation doesn't seem to actually create a signature. It just checks if the user provided signature is found and logs how many times.
It would be great to have signature creation like sigmaker for IDA.

**Comment by moradin** [comment]
Ok, so after more testing I now see that there are some cases where the signature is properly created but in some cases it's not. I am trying to create a signature to find the D3D9 device vptr in a 64bit dll. The bytecode is something like this:

```
00007FF995C954BE 48 8B D9             mov         rbx,rcx  
00007FF995C954C1 E8 22 BE FF FF       call        CD3DBase::CD3DBase (07FF995C912E8h)  
00007FF995C954C6 48 8D 05 1B 55 16 00 lea         rax,[CD3DHal::`vftable' (07FF995DFA9E8h)]  
00007FF995C954CD 48 89 03             mov         qword ptr [rbx],rax  
00007FF995C954D0 33 C0                xor         eax,eax  
```

the important part is the lea instruction so I select that and try to create a signature. What I get is actually just the first 5 bytes of the instruction. The problem with this is that the last 4 bytes can change in different versions of the dll (and I already have 2 different versions) so the signature will only work with that specific dll.

**Comment by Nukem9** [comment]
I knew this would come back to bite me eventually...if you want a shoddy workaround for now go to `Plugins > SwissArmyKnife > Options > Include RIP-relative addresses` and **uncheck** it. This will cause the entire LEA instruction to become ???????.
Until I find a better way to decode it, you will have to use the option above or edit the signatures by hand.

For example, the above code created by hand:

`\x48\x8B\xD9\xE8\x00\x00\x00\x00\x48\x8D\x00\x00\x00\x00\x00\x48\x89\x03\x33\xC0`
`xxxx????xx?????xxxxx`

**Comment by moradin** [comment]
Thanks, I can kinda use it this way so it's a good enough workaround for me.

**Comment by ghost** [comment]
Is this still an issue? I can't uncheck the option because it is greyed out for me.

**Comment by Nukem9** [comment]
RIP-relative instructions aren't a thing in 32-bit code. That's why it's grayed out. Generation behavior was changed in recent commits.
